# Generated by Django 4.2.23 on 2025-07-30 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='acousticness',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='song',
            name='danceability',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='song',
            name='duration_ms',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='song',
            name='energy',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='song',
            name='instrumentalness',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='song',
            name='key',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='song',
            name='liveness',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='song',
            name='loudness',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='song',
            name='mode',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='song',
            name='num_bars',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='song',
            name='num_sections',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='song',
            name='num_segments',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='song',
            name='rating',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_class',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='song',
            name='tempo',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='song',
            name='time_signature',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='song',
            name='valence',
            field=models.FloatField(),
        ),
    ]
